baseURL = "https://marcusnunes.me"
languageCode = "pt-br"
title = "Marcus Nunes"
theme = "hermit"
# enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
hasCJKLanguage = false  # If there're Chinese/Japanese/Korean Languages in the content, enable this.
rssLimit = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
googleAnalytics = "UA-201649-7"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
disqusShortname = "marcus-nunes-blog"

[author]
  name = "Marcus Nunes"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag = "tags"
  category = ""  # Categories are disabled by default.

[params]
  dateform        = "2 Jan, 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0300"

  # themeColor = "#494f5c"  # Theme color in meta tags.
  homeSubtitle = "Análises estatísticas descomplicadas"
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  # gitUrl = "https://github.com/mnunes/marcusnunes.me" # Prefix of link to the git commit detail page. GitInfo must be enabled.
  justifyContent = false  # Set "text-align: justify" to .content, requires extended version of Hugo
  # bgImg = ""  #  Homepage background-image URL

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.

  [[params.social]]
    name = "github"
    url = "https://github.com/mnunes"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/marcusanunes/"

  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/grandeabobora"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/_marcus_nunes_"

  [[params.social]]
    name = "email"
    url = "../contato/"

[menu]


  [[menu.main]]
    name = "Blog"
    url = "../posts/"
    weight = 0







